export enum ContentRating {
    GENERAL = 'GENERAL',
    PARENTAL_GUIDANCE = 'PARENTAL_GUIDANCE',
    MATURE_AUDIENCES = 'MATURE_AUDIENCES',
    MATURE_AUDIENCES_15 = 'MATURE_AUDIENCES_15',
    RESTRICTED_18 = 'RESTRICTED_18',
    RESTRICTED_X_18 = 'RESTRICTED_X_18',
    CHECK_THE_CLASSIFICATION = 'CHECK_THE_CLASSIFICATION',
    REFUSED_CLASSIFICATION = 'REFUSED_CLASSIFICATION',
    NOT_APPLICABLE = 'NOT_APPLICABLE'
}